### ISSUE TITLE
OS X: El Capitan logs mouse movements but not keystrokes

### ISSUE THREAD

**Issue by bergsalex** [gurgeh/selfspy#142]
I recently got selfspy to install on my mbp running osx verison 10.11.3. Aside from some wrangling with SIP, it wasn't too difficult. 
I've added

```
/usr/bin/python2.7
/usr/local/bin/selfspy
```

to my accessibility preferences using tccutil. I can run selfspy from the command line, and can do the following, which changes after I make some mouse clicks.

```
$ selfstats --clicks
0 keystrokes in 0 key sequences, 69 clicks (60 excluding scroll), 2805 mouse movements
```

My luck seems to end there however, since this is the output when I try several other selfstats commands (I'm leaving off some of the summary output).

```
$ selfstats --pkeys
0 keystrokes in 0 key sequences, 105 clicks (96 excluding scroll), 4784 mouse movements

$ selfstats -b 30 m
<RowID> <Starting date and time> <Duration> <Process> <Window title> <Number of keys pressed>
0 rows

$ selfstats
<RowID> <Starting date and time> <Duration> <Process> <Window title> <Number of keys pressed>
0 rows

$ selfstats -s
Password:
Do you want to store the password in the keychain [Y/N]: N
<RowID> <Starting date and time> <Duration> <Process> <Window title> <Number of keys pressed><Decrypted text>
0 rows
```

If I run

```
$ sqlite3 ~/.selfspy/selfspy.sqlite "SELECT * FROM window;"
1|2016-03-07 16:15:13.154197|1. Python|1
2|2016-03-07 16:15:13.336871|1. zsh|1
3|2016-03-07 16:15:25.569720|Search Results|2
```

I really appreciate any help you can offer. Thanks!

**Comment by samkrishna** [comment]
I'm glad @bergsalex had better luck than I did.

I'm running 10.11.4b6 (15E61b) and I did add `python` and `selfspy` via `tccutil`.

However, while it **claims** to be running, I can't seem to get **any** logging of any kind to happen.

Any suggestions would be appreciated.

**Comment by samkrishna** [comment]
OK, after enabling `python` via `tccutil`, I do seem to be caught up with where @bergsalex is in this issue.

**Comment by samkrishna** [comment]
@perelin mentioned a working solution to this issue [here](https://github.com/gurgeh/selfspy/issues/118#issuecomment-86202297):

Basically, use `nohup selfspy &` at the prompt to start and everything as intended.

Don't really know how to debug the "not starting at login" issue.

**Comment by bergsalex** [comment]
@samkrishna, that doesn't seem to make a difference on my system. Are you getting selfspy to record keystrokes when you use nohup? Is there anything else you might have done to get your setup working other than using nohup?

If all I change is starting selfspy with nohup, I have the exact same behavior as my initial post.

I'm going to attempt to update to 10.11.4 today and see if that makes a difference. Anything else you might have done to get this working would be greatly appreciated.

**Comment by bergsalex** [comment]
Updated to 10.11.4 and the problem persists. Not sure what else to try.

**Comment by samkrishna** [comment]
@bergsalex Did you also re-add both  

```
/usr/bin/python2.7
/usr/local/bin/selfspy
```

to Accessibility via `tccutil`? OS X might require that action for `selfspy` to work. I've been running 10.11.4 beta for a while before yesterday's final build update.

HTH.

**Comment by bergsalex** [comment]
Still no luck.

I added an [issue](https://github.com/jacobsalmela/tccutil/issues/14) to tccutil that I thought was related, but it seems not to be.

I've started modifying the selfspy code to get some debugging output and I've finally got some progress.

I added a print statement to sniff_cocoa.py on  `NSRightMouseDown` and sure enough, I get output when I make a right click. I still don't understand most of the program, but to me that means ~~that accessibility settings are set up correctly~~ that I've got no idea how Cocoa works.

**Comment by bergsalex** [comment]
I've got it working, but I've added so much to my accessibility settings that I'm not sure what finally did the trick. I'm now going to disable some until I find what breaks it again.

**Comment by bergsalex** [comment]
I can't believe this was the problem. I'm using iTerm2 rather than stock terminal. Adding that to my accessibility settings solved it.

**Comment by samkrishna** [comment]
That's awesome and a good reminder to make sure stuff is properly added to Accessibility. Congrats!

**Comment by bergsalex** [comment]
I'm using the following .plist file in ~/Library/LaunchAgents and it starts and seems to be fully functional at login. Not sure how to do this with a password protected database. If you use a python other than default, I think you'd just need to place `<string>/path/to/your/python</string>` above `<string>/usr/local/bin/selfspy</string>`.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>local.selfspy</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/selfspy</string>
        <string>-p</string>
        <string>""</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```
