### ISSUE TITLE
Fail to run on macOS Catalina

### ISSUE THREAD

**Issue by pablojvarela** [gurgeh/selfspy#176]
Hi!
I'm trying to run selfspy on macOS Catalina 10.15.2.

I get the following error:

```
/Users/pablovarela/envs/p2/bin/python2.7 /Users/pablovarela/src/selfspy/selfspy/__init__.py -p ""
Traceback (most recent call last):
  File "/Users/pablovarela/src/selfspy/selfspy/__init__.py", line 148, in <module>
    main()
  File "/Users/pablovarela/src/selfspy/selfspy/__init__.py", line 139, in main
    astore.run()
  File "/Users/pablovarela/src/selfspy/selfspy/activity_store.py", line 99, in run
    self.sniffer.run()
  File "/Users/pablovarela/src/selfspy/selfspy/sniff_cocoa.py", line 95, in run
    delegate = self.createAppDelegate().alloc().init()
  File "/Users/pablovarela/src/selfspy/selfspy/sniff_cocoa.py", line 58, in createAppDelegate
    class AppDelegate(NSObject):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector applicationWillResignActive of AppDelegate at 0x106156e68>

Process finished with exit code 1
```
It seems a problem with the objc and the Foundations (CoreFoundations python 2.7) call of AppDelegate().

I tried using the objc decorators `@objc.python_method` and the `@classmethod` decorators to no avail. 

Any pointers I could follow?
Thanks!

Pablo

**Comment by pablojvarela** [comment]
Also, thinking it may be a dependency problem, I migrated the python to python3 and installed newest versions of requirements.

Still, i get to the same exception as above.

**Comment by grandchild** [comment]
I am currently in the process of migrating the project to python3. Unfortunately it's not as simple as running 2to3, although it helps. What have you tried when you migrated it?

**Comment by pablojvarela** [comment]
I passed 2to3 and did debug runs fixing each exception and unassigned
variables.
See my pablojvarela/selfspy fork. Master branch has those changes (MacOS
only).

However the exception I'm getting is related to objc rather than the
interpreter version, don't you think?

**Comment by giansegato** [comment]
I have a working fork on Python3 as well. Check this out, may help: https://github.com/selfspy/selfspy/pull/174

**Comment by pablojvarela** [comment]
I found your branch by chance a couple of days ago!
I haven't tested it yet since I needed to switch to Linux.

Say, have you tested in on Catalina?
Did you hit/could you solve the pyobc complaining about the number of
arguments in the call to AppDelegate(NSObject)?

**Comment by giansegato** [comment]
I cannot really recall the fix (it was a few months ago), but as far as I remember, the latest version of that callback interface was slightly different. `applicationWillResignActive(self)` doesn't have `notification` parameter. So I got rid of it

See this line: https://github.com/selfspy/selfspy/pull/174/commits/e178e0459966a17f864be11c3a002bd8072e310d#diff-d301dec4475a0ccccb2e7a90e3069ab2R151

**Comment by pablojvarela** [comment]
@giansegato worked like a charm!
On Catalina.
