### ISSUE TITLE
Error on first usage

### ISSUE THREAD

**Issue by waldyrious** [gurgeh/selfspy#81]
All I did was install python-xlib:

    $ svn checkout svn://svn.code.sf.net/p/python-xlib/code/trunk python-xlib
    $ sudo python python-xlib/setup.py install

then selfspy:

    $ git clone git://github.com/gurgeh/selfspy
    $ sudo python selfspy/setup.py install

then I tried to run it:

```
$ selfspy
Password: 
Do you want to store the password in the keychain [Y/N]: y
RECORD extension present
Traceback (most recent call last):
  File "/usr/local/bin/selfspy", line 9, in <module>
    load_entry_point('selfspy==0.3.0', 'console_scripts', 'selfspy')()
  File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/__init__.py", line 124, in main
    astore.run()
  File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/activity_store.py", line 97, in run
    self.sniffer.run()
  File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/sniff_x.py", line 78, in run
    'client_died': False,
  File "/usr/local/lib/python2.7/dist-packages/Xlib/ext/record.py", line 121, in create_context
    ranges = ranges)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1418, in __init__
    self._binary = apply(self._request.to_binary, args, keys)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1103, in to_binary
    return apply(self.to_binary, varargs, keys)
  File "<string>", line 3, in to_binary
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 525, in pack_value
    data.append(self.type.pack_value(v))
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1117, in pack_value
    return apply(self.to_binary, (), value)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1103, in to_binary
    return apply(self.to_binary, varargs, keys)
  File "<string>", line 4, in to_binary
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 575, in check_value
    v = f.check_value(val[i])
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 588, in check_value
    raise TypeError('Object value must be tuple, dictionary or DictWrapper: %s' % val)
TypeError: Object value must be tuple, dictionary or DictWrapper: 0
```

What did I do wrong?

**Comment by blueyed** [comment]
Might be nice to have it working with python-xlib from trunk, too.

**Comment by gurgeh** [comment]
Yes. It would be even nicer to use a package that was in pypi, so the URLs were not needed. Theoretically.

**Comment by waldyrious** [comment]
@gurgeh as a python noob, is there anything I can do to help make this happen? Either the doc changes, getting it to work with trunk python-xlib, or with pypi packages. Any pointers welcome :)

**Comment by gurgeh** [comment]
@waldyrious When I first wrote this, there were no alternatives to python-xlib on pypi. There might be now, but probably not. Getting it to work with xlib 0.15 from the trunk is probably easy. I don't remember why we are on RC1. Probably we needed features from 0.15, but it was not properly released yet.

Anyhow, if you do the doc changes that you proposed and submit a pull-request, I will accept it.

**Comment by waldyrious** [comment]
@gurgeh I tried to re-test this before submitting a PR updating the docs, but ran into trouble again (let me know if this warrants a separate issue):

```
$ pip install svn+https://svn.code.sf.net/p/python-xlib/code/tags/xlib_0_15rc1
  ...
  Successfully installed python-xlib-0.15rc1

$ git clone git://github.com/gurgeh/selfspy
  ...
  Resolving deltas: 100% (417/417), done.

$ cd selfspy/ && sudo python setup.py install
  ...
  Finished processing dependencies for selfspy==0.3.0

$ selfspy
  Traceback (most recent call last):
    File "/usr/local/bin/selfspy", line 9, in <module>
      load_entry_point('selfspy==0.3.0', 'console_scripts', 'selfspy')()
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
      return ep.load()
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
      entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/__init__.py", line 31, in <module>
      from selfspy.activity_store import ActivityStore
    File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/activity_store.py", line 30, in <module>
      from selfspy import sniff_x as sniffer
    File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/sniff_x.py", line 23, in <module>
      from Xlib import X, XK, display
  ImportError: No module named Xlib
```

**Comment by gurgeh** [comment]
Could it be that "pip install" does not install to /usr/local but to your home path? I would try "sudo pip install ...xlib.."

**Comment by waldyrious** [comment]
Ah, yes, that was the case. I had installed anaconda earlier this month and apparently python-xlib was placed there. I will try on another machine to check whether sudo is required for the average case. (Or do you think we should recommend sudo regardless, just to be safe?)

Nevertheless, it sounds weird to my unexperienced ears that selfspy is correctly installed with a "Finished processing dependencies for selfspy==0.3.0" message, and then fails to execute by not finding those dependencies. Would it make sense for the installer to fail in such cases?

Additionally, while the Xlib module error has went away, now I get a similar error:

```
$ selfspy
Traceback (most recent call last):
  File "/usr/local/bin/selfspy", line 9, in <module>
    load_entry_point('selfspy==0.3.0', 'console_scripts', 'selfspy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/__init__.py", line 32, in <module>
    from selfspy.password_dialog import get_password
  File "/usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg/selfspy/password_dialog.py", line 21, in <module>
    from Tkinter import Tk, StringVar
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
```

It sounds like another case of a dependency issue not being detected during installation. I can install pyton-tk manually, as suggested by the error message, but I wonder if a generic fix could be applied to the setup script to prevent these problems.

**Comment by waldyrious** [comment]
(or maybe there's something wrong with my python setup, which is entirely possible, in which case any advice to clean it up is appreciated)

**Comment by blueyed** [comment]
Just a sidenote: you might want to try https://github.com/mitsuhiko/pipsi or pyenv for not messing with your system's Python.

**Comment by waldyrious** [comment]
@blueyed thanks for the tip. I had heard of pyenv before, but never quite grasped how to use it. Am I supposed to maintain separate "namespaces" for each set of python scripts? How do I know what is (in)compatible with what, and what I should install globally? Would I need to install common dependencies multiple times in each environment?

As a mostly consumer of python scripts, I tend to fall back to installing everything globally, so everything is available from everywhere. I'm sure that's a silly strategy, so if you have any recommendations about guides on how to best use these tools geared towards basic users, I'd greatly appreciate it!

**Comment by blueyed** [comment]
> Am I supposed to maintain separate "namespaces" for each set of python scripts?

Yes. It's meant to easily maintain virtualenvs per project (as a developer, or user), too.  (via pyenv-virtualenv).

> How do I know what is (in)compatible with what, and what I should install globally?

You would install nothing globally per se.  I have configured it to use 3.4.3 and 2.7.10 as my global version, which provides both Python 3 and 2 by default (preferring Python 3).
You could then globally install and upgrade e.g. `pip` or `flake8`.
But then for projects you would use `pyenv virtualenv 3.4.3 project` to create a new virtualenv based on 3.4.3 and then `pyenv local project` to use it from that directory.
You can always do `pyenv shell 2.7.10` to prefer (your) Python 2.
`pyenv shell system` would use the system's Python.
It's complex in the sense that it is very flexible.. :)

> Would I need to install common dependencies multiple times in each environment?

Yes.  I have that problem with the `neovim` package, which is required for Neovim's Python support.  But there are hooks you can use to install packages for new envs etc.

> As a mostly consumer of python scripts

Then give pipsi a try.  It is meant to provide a global `bin` namespace through separate virtualenvs for each project/program.

**Comment by blueyed** [comment]
..and you can mix pyenv and pipsi.  I also have pipsi for Python 2 and Python 3 (which is not straight-forward, but once you know that you can call a specific `pip` by its path, it gets easier).

**Comment by waldyrious** [comment]
> It's complex in the sense that it is very flexible.. :)

Yeah, that's how I see it. I feel like I don't need all that flexibility, I just want stuff to work well together :)

I'll give pipsi a try. I'll email you if I have more questions, to prevent polluting this thread further (or I can reach out in IRC or some gitter room if that's a possibility -- let me know), and when I get a good set of instructions that would work for python experts and newbies alike, I'll suggest a PR to improve the installation documentation.

**Comment by blueyed** [comment]
@waldyrious 
That sounds very reasonable and good.  You can reach me on IRC (Freenode, OFTC etc) with my nickname from here.  I should also have an email in my Github profile as a last resort.. ;)

Documentation PRs (also for pyenv etc) are very much appreciated!

:octocat:
